[project]
name = "pitstop"
version = "0.1.0"
description = "All-in-one F1 MCP Server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "feedparser>=6.0.11",
    "httpx>=0.28.1",
    "fastmcp>=0.4.0",
    "pydantic>=2.10.0",
    "python-dotenv>=1.0.0",
    "fastf1>=3.7.0",
]

[project.scripts]
pitstop = "pitstop.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/pitstop"]
